# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        font = QtGui.QFont()
        font.setPointSize(16)
        Dialog.setFont(font)
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(70, 20, 121, 20))
        self.label.setObjectName("label")
        self.nameEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.nameEdit.setGeometry(QtCore.QRect(210, 20, 113, 21))
        self.nameEdit.setText("")
        self.nameEdit.setObjectName("nameEdit")
        self.okButton = QtWidgets.QPushButton(parent=Dialog)
        self.okButton.setGeometry(QtCore.QRect(140, 70, 111, 31))
        self.okButton.setObjectName("okButton")
        self.nameLabel = QtWidgets.QLabel(parent=Dialog)
        self.nameLabel.setGeometry(QtCore.QRect(120, 160, 151, 16))
        self.nameLabel.setText("")
        self.nameLabel.setObjectName("nameLabel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Podaj swoje imie"))
        self.okButton.setText(_translate("Dialog", "OK"))
